language: ruby
script: 'bundle exec rake spec'
cache: bundler
rvm:
  - 2.0.0
  - 2.1.0
  - ruby-head
env:
  - RUBY_PLATFORM="x86_64-linux"
  - RUBY_PLATFORM="x86_64-darwin11.3.0"
  - CODECLIMATE_REPO_TOKEN=bccfad5e9dbca0688a4ee7d9bb5aa3e7ce943b910b8f52bdea5c6701c2378ef4
before_install:
  - git clone https://code.google.com/p/leveldb/
  - make -C $(pwd)/leveldb/
  - sudo cp --preserve=links leveldb/libleveldb.* /usr/local/lib
  - sudo cp -r leveldb/include/leveldb /usr/local/include/
  - sudo ldconfig
  - sudo apt-get install libopenal-dev
matrix:
  allow_failures:
    - rvm: ruby-head
  notifications:
    email:
      recipients:
        - ike18t@gmail.com
      on_success: change
      on_failure: change
