language: ruby
script: 'bundle exec rake'
cache: bundler
rvm:
  - 2.0.0
  - 2.1.0
  - ruby-head
env:
  - RUBY_PLATFORM="x86_64-linux"
  - RUBY_PLATFORM="x86_64-darwin11.3.0"
  - CODECLIMATE_REPO_TOKEN=bccfad5e9dbca0688a4ee7d9bb5aa3e7ce943b910b8f52bdea5c6701c2378ef4
before_install:
  - sudo apt-get update
  - sudo apt-get install libopenal-dev
  - sudo apt-get install npm
  - npm install npm -g
matrix:
  allow_failures:
    - rvm: ruby-head
  notifications:
    email:
      recipients:
        - ike18t@gmail.com
      on_success: change
      on_failure: change
